#!/usr/bin/env bash
# .copilot/bootstrap-oidc.sh
#
# One-shot Authentik OIDC bootstrap. Run AFTER uat-env-setup.sh has reported
# "OIDC NOT configured automatically". Creates the OAuth2/OpenID Provider
# and Application via the Authentik admin API using an API token previously
# created with `docker exec aiqadam-authentik-server ak shell -c '...'`.
#
# Usage:
#   bash .copilot/bootstrap-oidc.sh
#
# Reads:
#   .copilot/oidc-setup-token     - API token (d349...)
#   .copilot/oidc-provider-body.json  - provider POST body (already exists)
#
# Writes:
#   .copilot/oidc-bootstrap.env   - exports OIDC_CLIENT_ID and OIDC_CLIENT_SECRET
#   Patches apps/api/.env in place (OIDC_CLIENT_ID / OIDC_CLIENT_SECRET only).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOKEN_FILE="$REPO_ROOT/.copilot/oidc-setup-token"
BODY_FILE="$REPO_ROOT/.copilot/oidc-provider-body.json"
OUT_ENV="$REPO_ROOT/.copilot/oidc-bootstrap.env"
API_ENV="$REPO_ROOT/apps/api/.env"
AK_URL="http://localhost:9000"
FLOW_PK="1d66e442-fcbb-44ad-bd79-bcf44e21f9cf"   # default-provider-authorization-explicit-consent
INVAL_FLOW_PK="8b9a7847-f02e-44ab-a609-0016f714d841"   # default-provider-invalidation-flow
APP_NAME="AI Qadam Platform (local)"
APP_SLUG="aiqadam-platform-local"
REDIRECT_URI="http://localhost:4321/api/v1/auth/callback"

[[ -f "$TOKEN_FILE" ]] || { echo "FATAL: $TOKEN_FILE missing"; exit 1; }
TOKEN="$(cat "$TOKEN_FILE" | tr -d '\r\n[:space:]')"

if [[ -z "${TOKEN}" ]]; then
  echo "FATAL: token file is empty"
  exit 1
fi

echo "==> Using token from $TOKEN_FILE (len=${#TOKEN})"

# ── 1. Refresh the provider body with the correct flow PK (idempotent) ──────
cat > "$BODY_FILE" <<EOF
{
  "name": "aiqadam-platform-local-provider",
  "authorization_flow": "${FLOW_PK}",
  "invalidation_flow": "${INVAL_FLOW_PK}",
  "client_type": "confidential",
  "redirect_uris": [
    {"matching_mode": "strict", "url": "${REDIRECT_URI}"}
  ],
  "sub_mode": "hashed_user_id",
  "include_claims_in_id_token": true,
  "access_code_validity": "minutes=1",
  "access_token_validity": "minutes=10",
  "refresh_token_validity": "days=30"
}
EOF
echo "==> Provider body written to $BODY_FILE"

# ── 2. Check if provider already exists; skip creation if so ──────────────
echo "==> Checking for existing OAuth2/OIDC provider…"
existing_prov=$(curl -sS -H "Authorization: Bearer ${TOKEN}" \
  "${AK_URL}/api/v3/providers/oauth2/?name=aiqadam-platform-local-provider" \
  | jq -r '.results[0].pk // empty')
echo "    existing provider pk = '${existing_prov}'"

if [[ -n "${existing_prov}" ]]; then
  PROV_PK="${existing_prov}"
  echo "==> Reusing existing provider pk=${PROV_PK}"
else
  echo "==> Creating OAuth2/OIDC provider…"
  prov_resp=$(curl -sS -X POST \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    --data-binary "@${BODY_FILE}" \
    "${AK_URL}/api/v3/providers/oauth2/")
  PROV_PK=$(echo "${prov_resp}" | jq -r '.pk // empty')
  if [[ -z "${PROV_PK}" ]]; then
    echo "FATAL: provider creation failed. Response:"
    echo "${prov_resp}"
    exit 2
  fi
  echo "==> Provider created pk=${PROV_PK}"
fi

# ── 3. Extract client_id + client_secret (fetch fresh in case we reused) ────
echo "==> Reading client_id and client_secret from provider…"
prov_detail=$(curl -sS -H "Authorization: Bearer ${TOKEN}" \
  "${AK_URL}/api/v3/providers/oauth2/${PROV_PK}/")
CLIENT_ID=$(echo "${prov_detail}"   | jq -r '.client_id     // empty')
CLIENT_SECRET=$(echo "${prov_detail}" | jq -r '.client_secret // empty')

if [[ -z "${CLIENT_ID}" || -z "${CLIENT_SECRET}" ]]; then
  echo "FATAL: could not extract client_id/client_secret. Provider detail:"
  echo "${prov_detail}"
  exit 3
fi

echo "    client_id     = ${CLIENT_ID}"
echo "    client_secret = ${CLIENT_SECRET:0:8}…(${#CLIENT_SECRET} chars)"

# ── 4. Save exports to a file for the next stage to consume ───────────────
cat > "${OUT_ENV}" <<EOF
# Generated by .copilot/bootstrap-oidc.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
OIDC_CLIENT_ID=${CLIENT_ID}
OIDC_CLIENT_SECRET=${CLIENT_SECRET}
EOF
echo "==> Wrote ${OUT_ENV}"

# ── 5. Check / create the Application linked to this provider ─────────────
echo "==> Checking for existing application…"
existing_app=$(curl -sS -H "Authorization: Bearer ${TOKEN}" \
  "${AK_URL}/api/v3/core/applications/?slug=${APP_SLUG}" \
  | jq -r '.results[0].pk // empty')
echo "    existing app pk = '${existing_app}'"

if [[ -z "${existing_app}" ]]; then
  echo "==> Creating Application…"
  app_body=$(jq -n \
    --arg name "${APP_NAME}" \
    --arg slug "${APP_SLUG}" \
    --argjson provider "${PROV_PK}" \
    '{name:$name, slug:$slug, provider:$provider, meta_description:"UAT local instance"}')
  app_resp=$(curl -sS -X POST \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "${app_body}" \
    "${AK_URL}/api/v3/core/applications/")
  app_slug=$(echo "${app_resp}" | jq -r '.slug // empty')
  if [[ "${app_slug}" != "${APP_SLUG}" ]]; then
    echo "FATAL: application creation failed. Response:"
    echo "${app_resp}"
    exit 4
  fi
  echo "==> Application created slug=${app_slug}"
else
  echo "==> Reusing existing app pk=${existing_app}"
fi

# ── 6. Patch apps/api/.env (OIDC_CLIENT_ID + OIDC_CLIENT_SECRET only) ──────
echo "==> Patching ${API_ENV}"
if grep -qE '^OIDC_CLIENT_ID=' "${API_ENV}"; then
  sed -i.bak "s|^OIDC_CLIENT_ID=.*|OIDC_CLIENT_ID=${CLIENT_ID}|"     "${API_ENV}" && rm -f "${API_ENV}.bak"
else
  echo "OIDC_CLIENT_ID=${CLIENT_ID}" >> "${API_ENV}"
fi
if grep -qE '^OIDC_CLIENT_SECRET=' "${API_ENV}"; then
  sed -i.bak "s|^OIDC_CLIENT_SECRET=.*|OIDC_CLIENT_SECRET=${CLIENT_SECRET}|" "${API_ENV}" && rm -f "${API_ENV}.bak"
else
  echo "OIDC_CLIENT_SECRET=${CLIENT_SECRET}" >> "${API_ENV}"
fi
echo "==> Patched OIDC_CLIENT_ID and OIDC_CLIENT_SECRET"

echo ""
echo "==> Done. Verify with:"
echo "    curl -s ${AK_URL}/application/o/${APP_SLUG}/.well-known/openid-configuration | jq .issuer"