#!/usr/bin/env bash
# scripts/sync-ai-rules.sh
#
# Regenerates all tool-specific AI rule files from AGENTS.md + per-tool addons.
# Run via: pnpm ai:sync
#
# Output files (do NOT edit these by hand):
#   .github/copilot-instructions.md
#   .cursorrules
#   .cursor/rules/00-project.mdc
#   .windsurfrules
#   .clinerules
#   .kilocode/rules/00-project.md
#
# Source files (edit these):
#   AGENTS.md                         — shared rules for all tools
#   scripts/ai-rules-addons/*.md      — tool-specific additions
#
# Note: Kilo Code also reads AGENTS.md natively at the project root. The
# generated .kilocode/rules/00-project.md exists for discoverability inside
# .kilocode/ and to carry the Kilo-specific addon — it is not required for
# Kilo Code to pick up the shared rules.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS="$ROOT/AGENTS.md"
ADDONS="$ROOT/scripts/ai-rules-addons"

# Verify source files exist
if [[ ! -f "$AGENTS" ]]; then
  echo "ERROR: AGENTS.md not found at $ROOT/AGENTS.md" >&2
  exit 1
fi

for addon in copilot cursor windsurf cline kilocode cursor-mdc-header; do
  if [[ ! -f "$ADDONS/$addon.md" ]]; then
    echo "ERROR: addon file not found: $ADDONS/$addon.md" >&2
    exit 1
  fi
done

# ── Helpers ──────────────────────────────────────────────────────────────────

AUTOGEN_BANNER="<!-- AUTO-GENERATED by scripts/sync-ai-rules.sh -->
<!-- Edit AGENTS.md or scripts/ai-rules-addons/ — not this file. -->
<!-- Regenerate: pnpm ai:sync -->"

# generate <dest> <addon-file>
# Writes AGENTS.md + separator + addon content to dest
generate() {
  local dest="$1"
  local addon="$2"
  mkdir -p "$(dirname "$dest")"
  {
    echo "$AUTOGEN_BANNER"
    echo ""
    cat "$AGENTS"
    echo ""
    echo "---"
    echo ""
    cat "$ADDONS/$addon"
  } > "$dest"
  echo "  ✓  $dest"
}

# ── Generate flat tool files ──────────────────────────────────────────────────

echo "Syncing AI rule files from AGENTS.md..."
echo ""

generate "$ROOT/.github/copilot-instructions.md" "copilot.md"
generate "$ROOT/.cursorrules"                     "cursor.md"
generate "$ROOT/.windsurfrules"                   "windsurf.md"
generate "$ROOT/.clinerules"                      "cline.md"
generate "$ROOT/.kilocode/rules/00-project.md"     "kilocode.md"

# ── Generate Cursor v1 .mdc (frontmatter + body) ─────────────────────────────

MDC_DEST="$ROOT/.cursor/rules/00-project.mdc"
mkdir -p "$(dirname "$MDC_DEST")"
{
  # Frontmatter must be first in the file (no banner before it)
  cat "$ADDONS/cursor-mdc-header.md"
  echo ""
  echo "$AUTOGEN_BANNER"
  echo ""
  cat "$AGENTS"
  echo ""
  echo "---"
  echo ""
  cat "$ADDONS/cursor.md"
} > "$MDC_DEST"
echo "  ✓  $MDC_DEST"

echo ""
echo "Done. All AI rule files are up to date."
